
CREATE TABLE IF NOT EXISTS "public"."BoardLists" (
    "BoardId" integer NOT NULL,
    "ListId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."BoardMembers" (
    "BoardId" integer NOT NULL,
    "MemberId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."Boards" (
    "BoardId" integer NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT "now"() NOT NULL,
    "Title" "text",
    "UpdatedAt" timestamp without time zone
);

ALTER TABLE "public"."Boards" ALTER COLUMN "BoardId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Boards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Cards" (
    "CardId" integer NOT NULL,
    "Title" "text",
    "DueDate" "date",
    "Description" "text",
    "ReminderDate" "date"
);

CREATE TABLE IF NOT EXISTS "public"."CheckLists" (
    "CheckListId" integer NOT NULL,
    "IsChecked" boolean DEFAULT false,
    "Title" "text",
    "CardId" integer
);

ALTER TABLE "public"."CheckLists" ALTER COLUMN "CheckListId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CheckLists_CheckListId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Comments" (
    "CommentId" integer NOT NULL,
    "CreatedAt" time without time zone DEFAULT "now"() NOT NULL,
    "UpdatedAt" time without time zone,
    "Comment" "text",
    "CardId" integer
);

ALTER TABLE "public"."Comments" ALTER COLUMN "CommentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Comments_CommentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ListCards" (
    "ListId" integer NOT NULL,
    "CardId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."Lists" (
    "ListId" integer NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT "now"() NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "Title" "text"
);

ALTER TABLE "public"."Lists" ALTER COLUMN "ListId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Lists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Users" (
    "UserId" integer NOT NULL,
    "FirstName" "text",
    "LastName" "text",
    "Email" "text",
    "Password" "text",
    "Username" "text"
);

ALTER TABLE "public"."Users" ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE IF NOT EXISTS "public"."cards_cardid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY "public"."BoardLists"
    ADD CONSTRAINT "BoardLists_pkey" PRIMARY KEY ("BoardId", "ListId");

ALTER TABLE ONLY "public"."BoardMembers"
    ADD CONSTRAINT "BoardMembers_pkey" PRIMARY KEY ("BoardId", "MemberId");

ALTER TABLE ONLY "public"."Boards"
    ADD CONSTRAINT "Boards_pkey" PRIMARY KEY ("BoardId");

ALTER TABLE ONLY "public"."Cards"
    ADD CONSTRAINT "Cards_pkey" PRIMARY KEY ("CardId");

ALTER TABLE ONLY "public"."CheckLists"
    ADD CONSTRAINT "CheckLists_pkey" PRIMARY KEY ("CheckListId");

ALTER TABLE ONLY "public"."Comments"
    ADD CONSTRAINT "Comments_pkey" PRIMARY KEY ("CommentId");

ALTER TABLE ONLY "public"."ListCards"
    ADD CONSTRAINT "ListCards_pkey" PRIMARY KEY ("ListId", "CardId");

ALTER TABLE ONLY "public"."Lists"
    ADD CONSTRAINT "Lists_pkey" PRIMARY KEY ("ListId");

ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_Email_key" UNIQUE ("Email");

ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("UserId");

ALTER TABLE ONLY "public"."BoardLists"
    ADD CONSTRAINT "BoardLists_BoardId_fkey" FOREIGN KEY ("BoardId") REFERENCES "public"."Boards"("BoardId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."BoardLists"
    ADD CONSTRAINT "BoardLists_ListId_fkey" FOREIGN KEY ("ListId") REFERENCES "public"."Lists"("ListId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."BoardMembers"
    ADD CONSTRAINT "BoardMembers_BoardId_fkey" FOREIGN KEY ("BoardId") REFERENCES "public"."Boards"("BoardId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."BoardMembers"
    ADD CONSTRAINT "BoardMembers_MemberId_fkey" FOREIGN KEY ("MemberId") REFERENCES "public"."Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."CheckLists"
    ADD CONSTRAINT "CheckLists_CardId_fkey" FOREIGN KEY ("CardId") REFERENCES "public"."Cards"("CardId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Comments"
    ADD CONSTRAINT "Comments_CardId_fkey" FOREIGN KEY ("CardId") REFERENCES "public"."Cards"("CardId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ListCards"
    ADD CONSTRAINT "ListCards_CardId_fkey" FOREIGN KEY ("CardId") REFERENCES "public"."Cards"("CardId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ListCards"
    ADD CONSTRAINT "ListCards_ListId_fkey" FOREIGN KEY ("ListId") REFERENCES "public"."Lists"("ListId") ON UPDATE CASCADE ON DELETE CASCADE;